enabled: true
name: postgres-operator
namespace: cnpg-system

chart:
  repoURL: https://cloudnative-pg.github.io/charts
  name: cloudnative-pg
  version: "0.27.0"

valuesPath: platform-helm/postgres-operator/values.yaml
