folder('applications') {
    description('Application CI pipelines (generated by the seed job)')
}

applications.each { app ->

    def defaultBranch = app.source.branch ?: 'main'
    def cloneUrl = "https://github.com/${app.source.owner}/${app.source.repository}.git"

    multibranchPipelineJob("applications/${app.name}") {

        description("Automatic CI for ${app.name} on ${defaultBranch}. Pipeline logic lives in the pipeline-library shared library.")

        branchSources {
            branchSource {
                source {
                    github {
                        id(app.name)
                        repoOwner(app.source.owner)
                        repository(app.source.repository)
                        repositoryUrl(cloneUrl)
                        configuredByUrl(false)
                        credentialsId('github-credentials')

                        traits {
                            gitHubBranchDiscovery {
                                strategyId(1)
                            }
                            headWildcardFilter {
                                includes(defaultBranch)
                                excludes('')
                            }
                        }
                    }
                }
            }
        }

        factory {
            workflowBranchProjectFactory {
                scriptPath('Jenkinsfile')
            }
        }

        orphanedItemStrategy {
            discardOldItems {
                numToKeep(10)
            }
        }

        triggers {
            periodicFolderTrigger {
                interval('5m')
            }
        }
    }

    pipelineJob("applications/${app.name}-manual") {

        description("On-demand CI for ${app.name}. Builds any branch; the GitOps bump is opt-in.")

        parameters {
            stringParam('BRANCH', defaultBranch,
                        'Branch to fetch the Jenkinsfile from and build')
            booleanParam('UPDATE_GITOPS', false,
                         'Bump the image tag in the GitOps repo after pushing')
        }

        definition {
            cpsScm {
                scm {
                    git {
                        remote {
                            url(cloneUrl)
                            credentials('github-credentials')
                        }
                        // Expanded per build from the BRANCH parameter.
                        branch('${BRANCH}')
                    }
                }
                scriptPath('Jenkinsfile')
                lightweight(true)
            }
        }

        logRotator {
            numToKeep(20)
        }
    }
}
