folder('applications') {
    description('Application CI pipelines (generated by the seed job)')
}

applications.each { app ->

    multibranchPipelineJob("applications/${app.name}") {

        description("CI for ${app.name}. Pipeline logic lives in the pipeline-library shared library.")

        branchSources {
            git {
                id(app.name)
                remote(app.source.repository)
                credentialsId('github-credentials')
                includes(app.source.branch ?: 'main')
            }
        }

        factory {
            workflowBranchProjectFactory {
                scriptPath('Jenkinsfile')
            }
        }

        orphanedItemStrategy {
            discardOldItems {
                numToKeep(10)
            }
        }

        triggers {
            periodicFolderTrigger {
                interval('5m')
            }
        }
    }
}
