applications:

  - name: jarvis

    pipeline:
      template: docker-gitops
      version: "v1"

    source:
      repository: "https://github.com/ashish-splite/ai-agent-ts.git"
      branch: "main"

    image:
      repository: "thedarkest22/jarvis"

    gitops:
      repository: "https://github.com/ashish-splite/argo-infra.git"
      branch: "main"
      valuesFile: "applications/jarvis/chart/values.yaml"
      imageTagKey: ".image.tag"