enabled: true
name: postgres-pod
namespace: datastores
sourceType: external-helm

chart:
  repoURL: https://charts.bitnami.com/bitnami
  name: postgresql
  version: "15.5.20"

valuesPath: datastores/postgres-pod/values.yaml
