apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  namespace: {{ .Release.Namespace }}
  labels:
    cnpg.io/cluster: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    cnpg.io/cluster: {{ .Release.Name }}
    role: primary
