apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.clusterSecretStore.syncWave | quote }}
spec:
  provider:
    vault:
      server: {{ .Values.clusterSecretStore.provider.server | quote }}
      path: {{ .Values.clusterSecretStore.provider.path | quote }}
      version: {{ .Values.clusterSecretStore.provider.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.clusterSecretStore.credentials.secretName }}
          namespace: {{ .Release.Namespace }}
          key: {{ .Values.clusterSecretStore.credentials.key }}
