apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterSecretStore.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.clusterSecretStore.credentials.syncWave | quote }}
type: Opaque
stringData:
  access-key-id: {{ .Values.clusterSecretStore.credentials.accessKeyID | quote }}
  secret-access-key: {{ .Values.clusterSecretStore.credentials.secretAccessKey | quote }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.clusterSecretStore.syncWave | quote }}
spec:
  provider:
    aws:
      service: {{ .Values.clusterSecretStore.provider.service }}
      region: {{ .Values.clusterSecretStore.provider.region }}
      endpoint: {{ .Values.clusterSecretStore.provider.endpoint | quote }}
      auth:
        secretRef:
          accessKeyID:
            name: {{ .Values.clusterSecretStore.credentials.secretName }}
            namespace: {{ .Release.Namespace }}
            key: access-key-id
          secretAccessKey:
            name: {{ .Values.clusterSecretStore.credentials.secretName }}
            namespace: {{ .Release.Namespace }}
            key: secret-access-key
