apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ci-cd
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/ashish-splite/argo-infra.git
        revision: main
        files:
          - path: "ci-cd/*/app.yaml"
      selector:
        matchExpressions:
          - key: enabled
            operator: NotIn
            values: ["false"]
  template:
    metadata:
      name: "{{ .name }}"
    spec:
      project: default
      sources:
        - repoURL: "{{ .chart.repoURL }}"
          chart: "{{ .chart.name }}"
          targetRevision: "{{ .chart.version }}"
          helm:
            valueFiles:
              - $values/{{ .valuesPath }}
        - repoURL: https://github.com/ashish-splite/argo-infra.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
