apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-manifests
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/AshishRanjan9303/argo-infra.git
        revision: HEAD
        files:
          - path: "platform-manifests/*/app.yaml"
  selector:
    matchExpressions:
      - key: enabled
        operator: In
        values:
          - "true"
  template:
    metadata:
      name: "{{ .name }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/AshishRanjan9303/argo-infra.git
        targetRevision: HEAD
        path: "{{ .path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
