apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - git:
        repoURL: https://github.com/ashish-splite/argo-infra.git
        revision: main
        files:
          - path: "applications/*/app.yaml"
      selector:
        matchExpressions:
          - key: enabled
            operator: NotIn
            values: ["false"]

  template:
    metadata:
      name: "{{ .name }}"

    spec:
      project: default

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

  templatePatch: |
    {{- if eq .sourceType "external-helm" }}
    {{- if index . "extraManifests" }}
    spec:
      sources:
        - repoURL: "{{ .chart.repoURL }}"
          chart: "{{ .chart.name }}"
          targetRevision: "{{ .chart.version }}"
          helm:
            skipCrds: false
            valueFiles:
              - "$values/{{ .path.path }}/values.yaml"

        - repoURL: "https://github.com/ashish-splite/argo-infra.git"
          targetRevision: main
          ref: values

        - repoURL: "https://github.com/ashish-splite/argo-infra.git"
          targetRevision: main
          path: "{{ .path.path }}/chart"

    {{- else }}
    spec:
      sources:
        - repoURL: "{{ .chart.repoURL }}"
          chart: "{{ .chart.name }}"
          targetRevision: "{{ .chart.version }}"
          helm:
            skipCrds: false
            valueFiles:
              - "$values/{{ .path.path }}/values.yaml"

        - repoURL: "https://github.com/ashish-splite/argo-infra.git"
          targetRevision: main
          ref: values
    {{- end }}

    {{- else if eq .sourceType "git" }}
    spec:
      source:
        repoURL: "https://github.com/ashish-splite/argo-infra.git"
        targetRevision: main
        path: "{{ .path.path }}/chart"
        helm:
          releaseName: "{{ .name }}"
    {{- end }}
