enabled: false
name: prometheus
namespace: observability
valuesPath: observability/prometheus/values.yaml
chart:
  repoURL: https://prometheus-community.github.io/helm-charts
  name: kube-prometheus-stack
  version: 69.8.2
