ingress:
  enabled: true
  className: nginx
  paths:
    - path: /argocd
  # ArgoCD server service details
  backend:
    serviceName: argocd-server
    servicePort: 443
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/use-regex: "true"
