enabled: false
name: postgres-cluster
namespace: datastores
sourceType: external-helm
extraManifests: true

chart:
  repoURL: https://cloudnative-pg.github.io/charts
  name: cluster
  version: "0.4.0"
