applications:

  - name: jarvis

    source:
      owner: "ashish-splite"
      repository: "ai-agent-ts"
      branch: "main"

    image:
      repository: "thedarkest22/jarvis"

    gitops:
      repository: "https://github.com/ashish-splite/argo-infra.git"
      branch: "main"
      valuesFile: "applications/jarvis/chart/values.yaml"
      imageRepoKey: ".image.repository"
      imageTagKey: ".image.tag"
