replicaCount: 1

image:
  repository: thedarkest22/chat-interface
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  NODE_ENV: production
  LOG_LEVEL: info

ingress:
  enabled: true
  className: nginx
  host: chat-app.local
